### ISSUE TITLE
define metadata functionality in admiral (2h)

### ISSUE THREAD

**Issue by thomas-neitmann** [Roche-GSK/admiral#383]
goal:

what kind of functionality is required to use the metadata as discussed https://exbpbox.box.com/s/hf5gajmbmrjg02i3wvge1ubvuxl2dwh0

some ideas:
- Automatically select all predecessor variables from source dataset(s)
- Drop all variables in dataset which are not listed in spec
- Check actual variable type against type specified in spec
- Apply labels from spec to dataset
- Apply formats from spec to dataset
- Cross-check values of variables against controlled terminology in spec
- Apply length to variables when exporting (already covered in {xport}?)
- Automatically sort by keys provided in spec
- Derive a decode or code variable based on controlled terminology (e.g. you have SEX=M or F and then based on CT you can derived SEXN as 1 or 2 from a CT list)
- Sort variables within datasets as defined in the spec

Feel free to add.

**Comment by statasaurus** [comment]
all functions in metatools package please review from there
