### ISSUE TITLE
Update `derive_last_dose()`

### ISSUE THREAD

**Issue by bundfussr** [Roche-GSK/admiral#385]
- [x] Implement a general function which adds source variables from EX dataset like done within `derive_last_dose()`
- [x] Implement wrapper functions for last date, last dose, last dose group, ...
- [x] Explain in the documentation why it is necessary that start and end date of the dose coincide.

**Comment by bms63** [comment]
@bundfussr, @koegerr , @aehmann-gsk  The first task here - Implement a general function which adds source variables from EX dataset like done within **derive_last_dose()** .  Is this supposed to reference another function and not the function I am updating?

**Comment by bundfussr** [comment]
Hi @bms63 , the general function is a new function. The code should be almost the same as the current code of `derive_last_dose()`.  The difference is that the variables from EX are added without any transformation, e.g., it would add EXENDTC instead of converting it to  a date or datetime variable.
The conversion is done in the updated `derive_last_dose()` function, which calls the general function to add EXENDTC and then converts the DTC variable to a DT or DTM variable.
