### ISSUE TITLE
Add check for `min_dates` and `max_dates` parameters in `derive_vars_dt(m)()`

### ISSUE THREAD

**Issue by thomas-neitmann** [Roche-GSK/admiral#405]
Apparently a **list** of variable names is expected as input for these parameters. That wasn't clear to me and when I passed in  just a variable name I got a non-helpful error:

```r
data(ae)
data(adsl)

ae %>%
  left_join(adsl, by = "USUBJID") %>%
  derive_vars_dt(
      new_vars_prefix = "AST",
      dtc = AESTDTC,
      date_imputation = "first",
      min_dates = TRTSDT,
      max_dates = TRTEDT
    )
```
```
Error: Argument min_date = 15541 is not a lubridate date.
```

What should be issued instead is something like:

```
Error: `min_dates` must be a list of variable names
```

**Comment by hamzarahal** [comment]
@koegerr  the required check for min_dates and max_dates will impact the whole dates functions under derive_date_vars and not only derive_vars_dt to get the error message saying that the input for those parameters must be a list of variable names, which isn't the case for others date functions, 
So this should be a specific /local check only for derive_vars_dt ?

**Comment by thomas-neitmann** [comment]
@hamzarahal Please make this a specific check for the `derive_vars_dt()` and `derive_vars_dtm()` functions.

**Comment by hamzarahal** [comment]
@thomas-neitmann  using assert_vars() call for both min_dates and max_dates parameters, it gives the following :
" Error: `max_dates` must be a list of unquoted variable names, e.g. `vars(USUBJID, VISIT)`"
I guess it gives the same meaning comparing with the expected "Error: `min_dates` must be a list of variable names"?

**Comment by hamzarahal** [comment]
@thomas-neitmann for derive_vars_dtm(), I think no more need for the assert_character_vector(min_dates), we need to put assert_vars(min_dates/max_dates) instead, as we get "Error: `min_dates` must be a character vector but is `NULL`" even when min_dates() is not called
