### ISSUE TITLE
create vignette for unit testing guidance (3h)

### ISSUE THREAD

**Issue by koegerr** [Roche-GSK/admiral#453]
document: https://exbpbox.ent.box.com/file/828551143403

Ross will create a "how to do a unit test" guide see #625

**Comment by rossfarrugia** [comment]
@millerg23 i updated your file https://exbpbox.ent.box.com/file/828551143403 with some suggested additions and some comments where i need your help. the perspective i came at it from was one of a study programmer who might want to contribute to admiral but may have never even considered unit testing before, so i wanted to give a bit more basic instruction for them in addition to all your great tips. let me know what you think and hope you're ok to fill the gaps. once you're happy we could add this somewhere on the admiral site with the contributions guidance.
