### ISSUE TITLE
Clean up branches (1h)

### ISSUE THREAD

**Issue by slamao** [Roche-GSK/admiral#470]
There is a lot of branches (currently 57), I believe that most of them are no longer active / needed.

![image](https://user-images.githubusercontent.com/22340537/130224273-214fc614-7612-436d-a746-e497574ede26.png)

It would be good to clean this up before we make the repository public (or before we add many new users).

**Comment by bms63** [comment]
I use this command to get all the remote branches `git branch -a`

  

- [ ] remotes/origin/#463-update-to-programmingstrategy
- [ ] remotes/origin/130_sdtm_datasets
- [ ] remotes/origin/136_joined_vars
- [ ] remotes/origin/167_remove_merge_function
- [ ]   remotes/origin/170_roche_query
- [ ]   remotes/origin/171_query_gsk
- [ ]  remotes/origin/180_ex2adexmap
  remotes/origin/187_remove_exprs
  remotes/origin/189_adsl_vignette_updates
  remotes/origin/20_derive_param
  remotes/origin/223_merge_keys
  remotes/origin/240_read_dap_m3_eice
  remotes/origin/255_param_check
  remotes/origin/260_sdtm_datasets
  remotes/origin/266_git_usage
  remotes/origin/268_adcm
  remotes/origin/268_adcm_template
  remotes/origin/288_update_funs
  remotes/origin/300_worstfl
  remotes/origin/309_website_review
  remotes/origin/325_derive_param
  remotes/origin/326_use_ad_template_bug
  remotes/origin/332_derive_summary_records_bug
  remotes/origin/343_trigger_worklows_manually
  remotes/origin/355-update-faq
  remotes/origin/368_BSA
  remotes/origin/370_Vignette_QueryVar_ADCM
  remotes/origin/376_compute_date
  remotes/origin/379_co_to_parent
  remotes/origin/385_update_derive_last_dose_redux
  remotes/origin/395_derive_var_ontrtfl
  remotes/origin/397_derive_ATIREL
  remotes/origin/397a_update_derive_var_atirel_documentation
  remotes/origin/399_Update_Occurence_vignette
  remotes/origin/405_Add-check-for-min_dates-and-max_dates-parameters-in-derive_vars_dt(m)
  remotes/origin/41_fda_agegr_bug
  remotes/origin/425_drop_values_from
  remotes/origin/428_search_bar_website
  remotes/origin/433_remove_usethis_dependency
  remotes/origin/436_dtm_bug
  remotes/origin/437_update_derive_var_trtsdtm_bug
  remotes/origin/43_impute_date
  remotes/origin/521_deprecation
  remotes/origin/525_derivesummary
  remotes/origin/549_adtte_vignette
  remotes/origin/553_derive_extreme_flag_details_updt
  remotes/origin/561_query_dataset_doc
  remotes/origin/569_derive_agegr_update
  remotes/origin/572_adex_vignette
  remotes/origin/572_admiral_eric
  remotes/origin/572_adsl_vignette
  remotes/origin/572_faq_eric_2
  remotes/origin/572_git_usage_vignette
  remotes/origin/572_programming_strategy_eric
  remotes/origin/576_update_headers_kabis
  remotes/origin/583_dt_lst_source
  remotes/origin/583_source
  remotes/origin/593_documentation-of-derive_vars_dtm
  remotes/origin/599_validation_workflow
  remotes/origin/612_tte_sources
  remotes/origin/618_autovalidate_findings
  remotes/origin/62_derive_aval
  remotes/origin/639_exclude_sdtm
  remotes/origin/69_visit_flags
  remotes/origin/88_diffdf
  remotes/origin/94_lintr
  remotes/origin/95_r_env
  remotes/origin/HEAD -> origin/master
  remotes/origin/advs_demo
  remotes/origin/alice_junk
  remotes/origin/d
  remotes/origin/devel
  remotes/origin/gh-pages
  remotes/origin/initialize
  remotes/origin/lintr
  remotes/origin/master
  remotes/origin/s3

**Comment by thomas-neitmann** [comment]
@Roche-GSK/admiral-devs Plese see above and act accordingly.

**Comment by kabis-ops** [comment]
Hi I have checked the branches i want to keep.
