### ISSUE TITLE
Suggest adding units to derive_agegr_*

### ISSUE THREAD

**Issue by tgerke** [Roche-GSK/admiral#569]
The `derive_agegr_*` functions assume `age_var` is provided in years, but upstream functions like `derive_vars_aage()` helpfully allow specification of units. Here's an example of a breaking `derive_agegr_fda()`, where the patient is 35 but gets assigned to the 65+ group because `AAGE` was created in months. Adding a `unit` arg to `derive_agegr_*` (with a default to "years") could remedy this. 

```
dat <- tibble::tribble(
  ~BRTHDT, ~RANDDT,
  lubridate::ymd("1984-09-06"), lubridate::ymd("2020-02-24")
)

# oops
dat %>%
  derive_vars_aage(unit = "months") %>%
  derive_agegr_fda(AAGE, AGEGR1)
```

```
# A tibble: 1 x 5
  BRTHDT     RANDDT      AAGE AAGEU  AGEGR1
  <date>     <date>     <dbl> <chr>  <fct> 
1 1984-09-06 2020-02-24   425 MONTHS >=65  
```

**Comment by kabis-ops** [comment]
Thanks for the feedback/suggestion @tgerke, this definitively needs to be updated. 
May i please ask that you add a @Roche-GSK/admiral-devs to the discussion, so that we get notified 😃? Thank you

@aehmann-gsk - I have added this to the current sprint, but please move it if needed.

**Comment by bundfussr** [comment]
Maybe it is safer not to provide a default value for the `unit` parameter. We could first check if a unit variable is available (`age_var` with suffix "U") and if not, issue an error if the `unit` parameter was not specified.

**Comment by aehmann-gsk** [comment]
`AGEU` is a required ADaM variable so I agree with @bundfussr checking for `AGEU` should be sufficient especially in the context of calculating groups.

**Comment by thomas-neitmann** [comment]
So should we just specify `AAGEU` as a required variable and make sure to convert `AAGE` to `"YEARS"` in case `AAGEU` is something different? That way we wouldn't need a new function parameter at all.

**Comment by bundfussr** [comment]
`AGEU` is a required variable but `AAGEU` isn't. Thus I think we need the `unit` parameter to cover the case that there is no unit variable.
