### ISSUE TITLE
Review @seealso statements

### ISSUE THREAD

**Issue by esimms999-gsk** [Roche-GSK/admiral#574]
The @seealso info is not being done in a standard manner. Some have quotes, some do not; some have square brackets, some do not. Some do not resolve into links in the man file.

![image](https://user-images.githubusercontent.com/85294667/135474647-629bfbc3-e92e-42f6-bf73-d40110f299fe.png)

![image](https://user-images.githubusercontent.com/85294667/135480792-30b693ff-359d-4adf-bcc1-bdaa22972a64.png)

**Comment by thomas-neitmann** [comment]
Judging from [this article](https://roxygen2.r-lib.org/articles/rd-formatting.html) it appears that [function()] is the correct format. The square brackets create the link and it looks as tough the result is automatically typeset in a code font so the backticks are not necessary.

It would be good to change that and make everything consistent. @bms63 @yangc71 Does either of you want to take this on? It's a nice, little issue to get used to our GitHub workflow.

**Comment by yangc71** [comment]
I can update the @seealso statements to consistently use the [function()] format (so I can also test out if I'm understanding team's workflow correctly).
