### ISSUE TITLE
Implement `ignore_seconds` parameter for `derive_vars_dtm()`

### ISSUE THREAD

**Issue by bundfussr** [Roche-GSK/admiral#589]
Reviewer: Teckla, Samia

The ADaM IG states:
>For a given SDTM DTC variable, if only hours and minutes are ever collected, and seconds are imputed in *DTM as 00, then it is not necessary to set *TMF to "S".

To handle this case an `ignore_seconds` parameter should be added to `derive_vars_dtm()`. It should be defaulted to `FALSE`.

If it is set to `TRUE` and the DTC variable contains seconds, an error should be issued.

**Comment by bms63** [comment]
@bundfussr  Which function or functions is this now?  Is it still relevant?

**Comment by bundfussr** [comment]
The change affects `derive_vars_dtm()` and `compute_tmf()`.

**Comment by bms63** [comment]
Umm...Upon re-reading the issue.  Was I only supposed to ignore the flag.

**Comment by bundfussr** [comment]
Yes, the datetime variable should not be changed. Just the time imputation flag is affected.

**Comment by bms63** [comment]
Can the name of this parameter be slightly changed?  

`ignore_seconds `-  to me be would be ignoring the seconds in some capacity.  However, we are saying that the flag isn't needed.  

Should the parameter be ignore_seconds_flag

**Comment by bundfussr** [comment]
Fine with me.

**Comment by bms63** [comment]
This has been completed and merged into devel https://github.com/Roche-GSK/admiral/pull/746
