### ISSUE TITLE
review contribution model (30 min)

### ISSUE THREAD

**Issue by koegerr** [Roche-GSK/admiral#600]
goal: review and provide comments

https://exbpbox.box.com/s/thy52g281gueqesyocoveljmur1zlv11

**Comment by thomas-neitmann** [comment]
> I wonder how more general changes should be handled. For example, using metadata, providing a framework, creating a "log" file, ...

I think this exceeds the scope of an "outside" collaboration. These mroe fundamental discussion do require a dedicated core team like we have at the moment. Ideally, such questions are already answered by the time the package will become open source.

**Comment by rossfarrugia** [comment]
Good questions @bundfussr - as FYI this document is a useful read as a summary of all the admiral lead/sponsor brainstorms and thinking in this area so far: https://exbpbox.ent.box.com/file/815892983133?s=9gp0yr25ua657m0nz3bidf89qlszxiiy, but I also added a reply directly to your comment and questions on the doc Robin shared. I'm sure it will all evolve in time as well as we actually see in practice how much community contribution we get.

I would say no matter how big the request it still should go through an issue and same process, but for such more impactful strategy calls (if they ever arise) i'd say we should use our Slack user channel to reach out to the user community and get their input before making final decisions. a user community that feel engaged and listened to are likely to stay with using admiral, whereas if we ever made a decision some fundamentally disagree with then we risk them taking a fork and we lose potential contributors.

@koegerr doc looks a good start and i added some small comments. catch up with you this week and happy to help however needed to get this finalised prior to our open source license being added.

**Comment by koegerr** [comment]
Hi all, cleaned up the current document and added a new one for review. I hope it is clearer now.
I think key is that we explore this and extend/change where necessary.

**Comment by rossfarrugia** [comment]
Nice job. I like how succinct and clear this is as a first version to be tried out with some of our testing community. I added some small suggestions/comments, but feel free to accept/decline as you think best.

For future versions we could cover some of Stefan's points, such as how we could give acknowledgement to contributors and how we're open to evolving the constitution of our core team and our governance model over time, as we learn.

**Comment by bundfussr** [comment]
I have added some comments to the new document. (I am not sure if you get notifications for documents in box.)

**Comment by bundfussr** [comment]
@rossfarrugia , thanks for the information. It answers my questions. I wonder if we should communicate the information regarding governance. If other companies know that they may get invited to join the core team if they contribute a lot of type 1 requests, it may motivate them to contribute.

**Comment by rossfarrugia** [comment]
agree @bundfussr - i can talk through when presenting at the Dec 1st re-connect for now to share some high level ideas we have here, but will mention we're open to seeing how this progresses and the contribution levels before choosing the best path.

**Comment by rossfarrugia** [comment]
Now live on site https://roche-gsk.github.io/admiral/articles/contribution_model.html so closing this issue

**Comment by bms63** [comment]
@rossfarrugia 

Looks really good!  Love the image!!

Couple of things I noticed:

* Looks like a header didn't render properly.  
![image](https://user-images.githubusercontent.com/10111024/146780000-95e894eb-5cfd-4c02-a0f6-f98a620eb789.png)

* In the first bullet it says Git, but I think it should be GitHub
* In third bullet, it should be Github usage

Thanks!
