### ISSUE TITLE
Create common TTE sources

### ISSUE THREAD

**Issue by bundfussr** [Roche-GSK/admiral#612]
Create a file `tte_sources.R` where we pre-define common `tte_source` objects like death event, last alive censoring, first AE event, first serious AE event, .... To make users aware of them we should add them to `@seealso` in `derive_param_tte()` and `tte_source()` as well as add a dedicated section on the "References" section of our website.

**Comment by thomas-neitmann** [comment]
Thanks @bundfussr, I'll take it from here.

**Comment by thomas-neitmann** [comment]
Unless @kabis-ops wants to 😉

**Comment by kabis-ops** [comment]
@thomas-neitmann - please feel free to take care :)  I will  not have time now but I can make the review
