### ISSUE TITLE
create a "how to do a unit test" guide (3h)

### ISSUE THREAD

**Issue by koegerr** [Roche-GSK/admiral#625]
goal: create a hot to do guidance and add it to the vignette for unit testing (see #453)

**Comment by rossfarrugia** [comment]
updated https://exbpbox.ent.box.com/file/828551143403 but tagged Gordon at https://github.com/Roche-GSK/admiral/issues/453 to help me fill the gaps.

**Comment by millerg23** [comment]
I updated document based on Ross comments.  https://exbpbox.ent.box.com/file/828551143403
@thomas-neitmann or @kabis-ops  can you review and update sections around running the tests as a developer and anything you think needs added in the Automation section at the end.

**Comment by rossfarrugia** [comment]
thanks @millerg23 - i added one extra suggested sentence:
_Ensure you give a meaningful explanation of the test in the testthat call, as these will be compiled in the package validation report._
