### ISSUE TITLE
meet with metacore to decide on collaboration and issues

### ISSUE THREAD

**Issue by duniek** [Roche-GSK/admiral#643]
### DoD:
decide who will be focusing on metacore package testing from admiral team
ask metacore dev. team how they want to work together.
Ideally, we see ourselves as metacore package testers and expect metacore team to develop based on feedback/input.
- Create issues in our Scrum board!

Also, ask metacore dev team if they would assess specs collected from admiral testing companies.
Invite:
Mike
Christina
?

**Comment by rossfarrugia** [comment]
Meeting placeholders sent for Dec 9th or 10th
