### ISSUE TITLE
Creating a BDS Finding ADaM - overwriting advs

### ISSUE THREAD

**Issue by bms63** [Roche-GSK/admiral#646]
I'm using advs to explore xportr package and spec files.  I noticed that advs is overwriting itself as you step through the example.  Is is okay to have it as intermediate datasets?  I find this helpful when you want to see how 4 or 5 intermediate datasets interact with each other.  At this time, they go overwrite each and I have to go back and remember which one is which and/or rerun the code.  Anyways not a super pressing issue!  

I'm happy to take on this update if others are think it is worthwhile.

![image](https://user-images.githubusercontent.com/10111024/140819014-fb105ae4-7542-420b-969a-395021d410db.png)

**Comment by thomas-neitmann** [comment]
I feel like we already had a discussion about that at some point with @millerg23. There's pros and cons to overwriting or creating new intermediate datasets.

**Comment by millerg23** [comment]
Hi @bms63 ,
I raised same issue when I was updating the ADVS script, it was felt that users would copy paste certain parts of the code or remove certain function calls, so they would potentially have to update the input and output datasets.
I think we should have some kind of recommendation or good practice document that would suggest to have different names for the intermediate datasets. Possibly explain why we always have ADVS. Maybe this could be done at the top of each script?

**Comment by thomas-neitmann** [comment]
@bms63 Is there anything actionable we can take from this issue or should we close?

**Comment by bms63** [comment]
We can close it
