### ISSUE TITLE
Creating a BDS Finding ADaM - paramcd - MAP not updating to Mean Arterial Pressure (mmHg)

### ISSUE THREAD

**Issue by bms63** [Roche-GSK/admiral#650]
This was caught in the P21 Report that I was working on!  Looks like MAP is not getting updated to Mean Arterial Pressure (mmHg) in the vignetter

![image](https://user-images.githubusercontent.com/10111024/141004999-cedd80bd-0353-46d9-b94f-2d324f6de46e.png)

![image](https://user-images.githubusercontent.com/10111024/141005342-0ee23f16-f7a3-4f74-a836-af5d36741c4b.png)

**Comment by bms63** [comment]
Actually I think this is related to the merge issue as STUDYID and a lot of other variables are empty for the 8,886 obervations

**Comment by thomas-neitmann** [comment]
That doesn't look right. Feel free to open a PR to fix this,

**Comment by bms63** [comment]
@millerg23 Hey Gordon, I noticed this issue is still present in the ad_advs.R script.  Is it fixed in the vignette for 0.4 Release.  I was trying to work through it but it super long! :)

**Comment by millerg23** [comment]
@bms63 Hi Ben,
Where are you reading the script from, DEVEL or MASTER? The one in DEVEL should not have this issue.
Let me know if thats not the case, and I can delve deeper.
Regards,
Gordon,

**Comment by bms63** [comment]
@millerg23  I was running it in the pre-release branch.  Maybe that hasn't been synced up with devel?

**Comment by millerg23** [comment]
@bms63 Hi Ben,
It seems OK to me, maybe we can catch up tomorrow and take a look.
I am just logging off for the evening.
Regards,
Gordon.

**Comment by millerg23** [comment]
Hi @bms63 
I realised it was the Vignette you were referencing before, I have taken a look.
We have the following in the Vignette after "Assign PARAMCD, PARAM, PARAMN, PARCAT1" section:
```
At this stage, only PARAMCD is required to perform the derivations. Additional derived parameters may be added, so only PARAMCD is joined to the datasets at this point. All other variables related to PARAMCD (e.g. PARAM, PARAMCAT1, …) will be added when all PARAMCD are derived.

advs <- left_join(advs, select(param_lookup, VSTESTCD, PARAMCD), by = "VSTESTCD")
 ```

And then again after "Derive Additional Parameters (e.g. BSA, BMI or MAP for ADVS)" section:
```
When all PARAMCD have been derived and added to the dataset, the other information from the look-up table (PARAM, PARAMCAT1,…) should be added.

# Derive PARAM and PARAMN
advs <- left_join(advs, select(param_lookup, -VSTESTCD), by = "PARAMCD")
```

So you would only run the left_join to the lookup once, depending on what parameters you are creating.
Does that make sense? Can we close this ticket, or do you think Vignette needs to be clearer?

**Comment by bms63** [comment]
I think it is fine!  Will close thanks for the clarity
