### ISSUE TITLE
Test website release

### ISSUE THREAD

**Issue by kabis-ops** [Roche-GSK/admiral#651]
- News
- Documentation of new functions
- New vignettes

**Comment by thomas-neitmann** [comment]
@Roche-GSK/admiral-devs To complete this task, please checkout the `pre_release` branch, restart your R session, run `renv::restore()` (to install the {admiral.test} package) and then run `pkgdown::build_site()` to build the website locally.

Please address any inding you encounter directly inside the `pre_release` branch and push your changes. Ideally you comment your findings prior to that here sucht that others are aware and we do not duplicate work. As mentioned in the comment above, please focus your review on the `NEWS.md` file, documentation pages of new function (make sure to check examples!) and new vignettes.

**Comment by bundfussr** [comment]
@Roche-GSK/admiral-devs , the `NEWS.md` looks quite incomplete. I am not sure how we should fix it. How can we identify the issues affecting this release? @thomas-neitmann , how did you do it for the releases before?

**Comment by bundfussr** [comment]
I am going to add the new vignettes to `NEWS.md`.

**Comment by thomas-neitmann** [comment]
@bundfussr Last time I looked through all pull requests closed since the last release and identified issues that way. Will start doing the same today.

**Comment by thomas-neitmann** [comment]
I'm going to remove the "SDTM datasets" section on the reference page as these datasets have been moved to {admiral.test}.

**Comment by thomas-neitmann** [comment]
ADAE and ADCM are not listed on the website.

**Comment by thomas-neitmann** [comment]
I'm going to add a new section for the `tte_source` objects.

**Comment by thomas-neitmann** [comment]
The output variables of `derive_vars_dtm_tm()` are not displayed in the examples. 

![image](https://user-images.githubusercontent.com/11788080/141789640-658346ec-d8fd-470c-a00e-a649ef48706d.png)

**Comment by bundfussr** [comment]
There are also some typos in the documentation and the `hms` package is not mentioned.

**Comment by bundfussr** [comment]
@thomas-neitmann , are you going to update `derive_vars_dtm_to_tm()` or should I do it?

**Comment by thomas-neitmann** [comment]
I've pushed some updates to that function.

**Comment by bundfussr** [comment]
The programing flow and the sections are out of sync in the ADSL vignette. I will update them.

**Comment by bundfussr** [comment]
On the OCCDS vignette the links to the scripts are missing. I will add them.

**Comment by bundfussr** [comment]
The programing flow and the sections are out of sync in the BDS Findings vignette. I will update them.

**Comment by thomas-neitmann** [comment]
@hamzarahal is missing as a author in DESCRIPTION. I'll add him.

**Comment by thomas-neitmann** [comment]
`tte_source()`, `event_source()` and `censore_source()` are missing examples. The latter to also don't have a link to `derive_param_tte()`. I'll update.

**Comment by bundfussr** [comment]
For me the loading of some of the vignettes takes quite a long time and is producing messages that the page is not responding. Do you observe the same?
I guess it is due to the size of some of the interactive tables. We could shorten those with more than 1000 observations.
What do you think?

**Comment by thomas-neitmann** [comment]
I do not get this message... Could you post a screenshot? However, in general I agree that 1000 observations shouls be more than sufficient.

**Comment by thomas-neitmann** [comment]
@bundfussr I feel like we should **not** export the `tte_source()` function. This might leaad to confusion for users. If they use `tte_source()` directly rather than `event_source()` and `censor_source()` they would get an error when passing the objects into `derive_param_tte()`.

**Comment by bundfussr** [comment]
I get the message for the BDS finding and BDS exposure vignette.
![image](https://user-images.githubusercontent.com/80953585/141952444-e0bc26f0-5347-4426-af71-17572bf4b490.png)

**Comment by thomas-neitmann** [comment]
Same here with those vignettes. The wheel keeps spinning but the tables are not displayed. Let's make `dataset_vignette()` display only a subset of rows.

**Comment by bundfussr** [comment]
@thomas-neitmann , I agree, we need `tte_source` only internally.

**Comment by bundfussr** [comment]
I would add the restriction rather in the call than in the function because otherwise it could happen that the observations of interest are not displayed, e.g., if summary records are added at the end of the dataset.
What do you think?

**Comment by thomas-neitmann** [comment]
That sounds like a rather manual process :/

How about we restrict the number of subjects in `ADVS` at the start of the vignette to only a subset?

**Comment by bundfussr** [comment]
OK, I'll try to restrict VS and EX at the beginning.

**Comment by bundfussr** [comment]
In the documentation of the ADaM datasets the link to the script is out of date. I'm going to fix it.
