### ISSUE TITLE
Rethink interface of baseline related derivations

### ISSUE THREAD

**Issue by thomas-neitmann** [Roche-GSK/admiral#695]
Several tester indicated that they found the naming of `derive_baseline()` to be confusing as they expected it to derive the baseline flag. In addition, questions where raised whether there's a need to have `derive_var_base()` and `derive_var_basec()` if you can use the underlying function to create those witht the added benefit of more explicit code as you would have to specify the `source_var` and `new_var` when using `derive_baseline()`.

My suggestion would be to rename `derive_baseline()` to `derive_var_base()` and remove `derive_var_basec()`.

**Comment by thomas-neitmann** [comment]
Fyi @Roche-GSK/admiral-devs

**Comment by thomas-neitmann** [comment]
In addition we were asked to allow the input of a user specifyed baseline definition rather than hard-coding `ABLFL == "Y"`.

**Comment by bundfussr** [comment]
Should we change the programming strategy? At the moment we have:
> Please note that *var* prefix should be used only if the function name includes the name of the variable (e.g. `derive_var_ady()`). It should not be used if the variable name is supplied as an argument (e.g. `derive_baseline()`, which has a `new_var` argument).

**Comment by thomas-neitmann** [comment]
I think so, yes. Probably we should use the `var` prefix for every function that creates a new variable, also those that have a `new_var` parameter.

**Comment by bundfussr** [comment]
Should we create a separate issue for updating the programming strategy and renaming the functions?
