### ISSUE TITLE
Remove `context()` calls in test scripts

### ISSUE THREAD

**Issue by thomas-neitmann** [Roche-GSK/admiral#710]
From the [testthat 3rd edition vignette](https://testthat.r-lib.org/articles/third-edition.html):

> `context()` is formally deprecated. testthat has been moving away from `context()` in favour of file names for quite some time, and now you’ll be strongly encouraged remove these calls from your tests.

**Comment by thomas-neitmann** [comment]
@Roche-GSK/admiral-devs A nice little issue for someone with a bit of spare time 😉

**Comment by bms63** [comment]
When we remove context in the test files.  Do we need to do anything else with the test file.   Some type of header block?

![image](https://user-images.githubusercontent.com/10111024/145135200-8e9dcc96-4e89-4def-b4ae-4f99f52d4947.png)

**Comment by thomas-neitmann** [comment]
No, nothing else required. This used to be the ID for the tests when running `devtools::test()` but now they just use the file name as ID. Please make sure to also remove any blanks lines after the `context()` call such that the test files do **not** start with empty lines.

**Comment by bms63** [comment]
Should we put this into the Unit Testing guide - that some files might have context and it should be removed? 
![image](https://user-images.githubusercontent.com/10111024/145213548-43185ead-0b95-4b8b-bd25-7b0bb7cb1a9a.png)

**Comment by bms63** [comment]
lol i see ive been assigned this update

**Comment by thomas-neitmann** [comment]
It looked like you volunteered to me 😉
