### ISSUE TITLE
Correct example for `derive_params_exposure()`

### ISSUE THREAD

**Issue by bundfussr** [Roche-GSK/admiral#722]
There is a typo in the `filter` parameter of the second example ("average dose in w2-24"): "WEEK2" instead of "WEEK 2"

The values of `USUBJID` in the examples should be shortened such that the subjects are distinguishable, e.g., by removing the "01-701-" part.

**Comment by thomas-neitmann** [comment]
Btw, why is the function call derive_param**s**_exposure() and not derive_param_exposure? If I correctly remember our discussion it only adds a single parameter per call. If so, then we should rename it accordingly.

**Comment by bundfussr** [comment]
I agree that we should remove the "s". I think the only function which could add more than one parameter is `derive_param_tte()` and this is without "s".

**Comment by rossfarrugia** [comment]
@thomas-neitmann @bundfussr i'd like to test out our contribution model putting myself in the shoes of an external contributor (well technically i am having contributed zero admiral code thus far!), so is it OK to assign this issue to me? no problem if someone else is already picking it up

**Comment by bundfussr** [comment]
@rossfarrugia , I do not think that anyone is working on this already. So feel free to assign it to you.

**Comment by rossfarrugia** [comment]
thanks @bundfussr i will pick it up. @thomas-neitmann i don't have permission to assign people to admiral issues so please assign me

**Comment by thomas-neitmann** [comment]
@rossfarrugia Great initiative 👏 

I just gave to "write" access to the repository. You should now be able to assign yourself (or anyone else for that matter) and push new branches to the repo. Good luck 😉

**Comment by rossfarrugia** [comment]
@bundfussr i'm shamed by how long that took me this morning, but good learning nonetheless! i updated the derive_params_exposure R program to rename to param instead of params and updated the examples, and i updated the corresponding unit test program with params->param. see the pull request linked above. shout if i missed anything!

@thomas-neitmann this [page](https://roche-gsk.github.io/admiral/articles/git_usage.html) is excellent!
