### ISSUE TITLE
review metadata proposal for Metacore meeting (1h)

### ISSUE THREAD

**Issue by koegerr** [Roche-GSK/admiral#732]
please review the slides and let me know if anything is unclear or if you disagree

https://exbpbox.box.com/s/bos49n655nqgvwk8i4hymmedqpjqi6q3

**Comment by bms63** [comment]
@koegerr Looking good.  Maybe we should think on a common excel spreadsheet that we recommend for everyone to use.  The best candidate would be the p21 spec template.  That way we can make the user bend to our will rather then building in contingencies or checks for every single company's nuanced spec file?!?

Also, a lot of the functionality requested here is already available in the xportr package via a spec file or a metacore object.  Hopefully we can bring that stuff into metacore and not rebuild from scratch.

I'm still a big fan of keeping metadata functions, etc split out from the admiral package.   Gives a more pharmaverse feel to it and gets Atorus more involved with this process.  I guess a problem is if they become out of sync from each other or Atorus gives up on metacore...not likely!

**Comment by thomas-neitmann** [comment]
> Also, a lot of the functionality requested here is already available in the xportr package via a spec file or a metacore object. Hopefully we can bring that stuff into metacore and not rebuild from scratch.

I'd really like to see the existing code being migrated to metacore as I don't think this should sit in xports. Even if I exported to another format I want to make sure that the available metadata is being leveraged.
 
> I'm still a big fan of keeping metadata functions, etc split out from the admiral package.

I agree with that, especially given that we promote the pharmaverse we should make sure that each package fills its niche and that the packages leverage each others strengths.

**Comment by koegerr** [comment]
> @koegerr Looking good. Maybe we should think on a common excel spreadsheet that we recommend for everyone to use. The best candidate would be the p21 spec template. That way we can make the user bend to our will rather then building in contingencies or checks for every single company's nuanced spec file?!?

I think we cannot really force companies to use one spec file. The idea is that Metacore provides the harmonized layer, while its each companies workflow how to load their metadata into it. Could also be done via a define file, but these often don't exist till the very end of the study/shortly before submission.

As Thomas said. Just creating the metadata while creating XPT files would not be sufficient due to:

- data fairness
- data readability (I need labels :)) 
- XPT often is only created for submission
- having metadata checks in place before even creating XPT

Hope that helps.

**Comment by bms63** [comment]
Well not force - but encourage them.  I was just thinking it would be easier to program everything if we have a "gold standard" that we can share.  When developing xportr and metacore with Atorus and GSK and the two difference spec files were a bit cumbersome.  I think everyone has very similar spec files anyways - probably not going to a big issue.   I was just thinking in terms of our programming.

I'm a bit confused about the second point @koegerr.  The xportr package doesn't just output the xpt files with the metadata - that is its last purpose.  It first applies all format, types, lengths, labels, etc from spec or metacore object but you don't have to send them out to xpt file.  For example, you can apply all the lables from the spec file and view them in R as an object and never touch anything with formats or lengths.  

Yes on the checks!  There is messaging around missing labels, label lengths, formtas, etc built-in to xportr.  hopefully that makes it over to metacore as there seems to be requests for checks/messaging around assigning metadata.

**Comment by thomas-neitmann** [comment]
@bundfussr Agree with your point on computations. That feels like something that should find its home in admiral.

**Comment by koegerr** [comment]
> I'm a bit confused about the second point @koegerr. The xportr package doesn't just output the xpt files with the metadata - that is its last purpose. It first applies all format, types, lengths, labels, etc from spec or metacore object but you don't have to send them out to xpt file. For example, you can apply all the lables from the spec file and view them in R as an object and never touch anything with formats or lengths.

That sounds good. Thomas and myself did understand it that this is part of XPT file creation not like a stand alone functionality.
If that covers all the needs and the performance is good I think we could keep it.



> ach company needs to figure out how to get their specs into a format Metacore can read. I made use of the define_to_metacore function to read in GSK's general ADaM specs in define.xml format. The define.xml is an industry standard. I don't think there is any industry standard for this in Excel format; Metacore has a spec_to_metacore function which states "_This function takes the location of an excel specification document and reads it in as a meta core object. At the moment it only supports specification in the format of pinnacle 21 specifications. But, the @family spec builder can be used as building blocks for bespoke specification documents".

As far as I know Thomas was able to read in Roche specs which are different to P21 specs. What I tried to say was that this is a company issue to solve. I do not see the admiral team in a position to figure out what the best way how to store the companies Metadata in Metacore if that makes sense. 

> @bundfussr Agree with your point on computations. That feels like something that should find its home in admiral.

Agree as well. Just wanted to see how people feel about it or if there is already something in the backlog of Metacore.

**Comment by lucyhoch** [comment]
Looks good, I have no specific comments, I think it frames the discussion.  I do think metacore will push back on to many additions to metacore and I think to have the basic metadata functions in admiral makes sense as an add on
