### ISSUE TITLE
Andrew S. onboarding to admiral

### ISSUE THREAD

**Issue by teckla-gsk** [Roche-GSK/admiral#740]
### Access:
- [x] box
- [x] github
- [x] admiral_dev
- [x] admiral
- [ ] admiral_testing_01
### Ways of working?
- [ ] Ways of working?

**Comment by bms63** [comment]
Hi Andrew!

Welcome to admiral.  Check out these articles on the packagedown site for a good overview of the strategy and process in admiral.

![image](https://user-images.githubusercontent.com/10111024/145215703-5aad5512-0d1e-44f2-b4a5-75ed9f02ceb1.png)

https://roche-gsk.github.io/admiral/index.html
