### ISSUE TITLE
notin function not being loaded if adsl template is followed

### ISSUE THREAD

**Issue by teckla-gsk** [Roche-GSK/admiral#744]
In format_dcsreas  section of adsl template notin was not being loaded as part of admiral??? Something to investigate

**Comment by thomas-neitmann** [comment]
Could you elaborate? I don't quite get it...

**Comment by rossfarrugia** [comment]
@teckla-gsk @thomas-neitmann i was just working on another ADSL template issue so i looked into this. it's not actually used in the template but it is referenced in a section of the ADSL vignette here: https://roche-gsk.github.io/admiral/articles/adsl.html#disposition_reason, where it talks about "Example function format_dcsreas():"

the function "notin" is covered here https://roche-gsk.github.io/admiral/reference/grapes-notin-grapes.html and is covered by our utils.R code. i tried running the ADSL vignette code extract and it worked for me.

i think ok to close this issue, but feel free to re-open if you think i missed anything.

**Comment by thomas-neitmann** [comment]
We probably should not use `%notin%` in the `format_dcsreas()` ` function. The former is only meant for internal purposes but the latter s exposed to users which could lead to confusion. Instead of `a %notin% b` we can just use `!a %in% b`.

**Comment by rossfarrugia** [comment]
thanks @thomas-neitmann - now updated
