### ISSUE TITLE
Combine 2 unit testing guidances

### ISSUE THREAD

**Issue by rossfarrugia** [Roche-GSK/admiral#769]
@millerg23 - FYI @bundfussr spotted that we have 2 separate unit testing guides now [here ](https://roche-gsk.github.io/admiral/articles/programming_strategy.html#unit-testing-1) and [here](https://roche-gsk.github.io/admiral/articles/unit_test_guidance.html). i have to say, i spotted the same before and had wondered about this but didn't act on it.

my proposal would be to include all this text only in the unit testing guidance, and remove from the programming strategy page. that paragraph actually would make a good intro if included in the unit testing guide under "Writing Unit Tests in {admiral}".

what do you think? i assigned you for now given you already worked on this before.

**Comment by millerg23** [comment]
Thanks @rossfarrugia , there is quite a lot of overlap, I will add some extra info from the programming strategy into the Guidance, and remove the section about Unit Tests. Alternatively we could add a link from the programming strategy to the Guidance.

**Comment by bundfussr** [comment]
I would not remove the "Unit Testings" section from the programming strategy but replace it by something like

>A function requires a set of unit tests to verify it produces the expected result. See Writing Unit Tests in {admiral} for details.

**Comment by rossfarrugia** [comment]
That makes sense to me Stefan, either way we're attracting people towards one single place and putting unit testing on their radar as an important piece they need to be aware of. Thanks Gordon, appreciate you taking this on!
