### ISSUE TITLE
Make lintr workflow error when any issue has been detected

### ISSUE THREAD

**Issue by thomas-neitmann** [Roche-GSK/admiral#773]

**Comment by bundfussr** [comment]
What should we do regarding the cyclomatic complexity warnings?

**Comment by thomas-neitmann** [comment]
I suppresed these for the two function that have this warning currently using `# nolint`.

**Comment by bundfussr** [comment]
@thomas-neitmann , it seems that the lintr warning are no longer displayed in github. Could you check please?

**Comment by thomas-neitmann** [comment]
I noticed this as well. Will look into it.

**Comment by thomas-neitmann** [comment]
Closing in favor of #789.
