### ISSUE TITLE
github usage vignette overwritten

### ISSUE THREAD

**Issue by bms63** [Roche-GSK/admiral#792]
Just noticed that the github usage vignette i updated a few weeks ago got overwritten with the old one.  Will investigate tomorrow, but if you see anything amiss can you take a look

**Comment by rossfarrugia** [comment]
@bms63 that's funny... i remember reading your original version with lines like "Pictures are nice too..." included and then one day i went back and it wasn't there. i thought it was just me - i was really confused. i must have been reading the latest devel version and not from the site, i realise now.

i checked and your updates are all here https://github.com/Roche-GSK/admiral/pull/674, but they just haven't been merged into master yet. if you look at master for this program on the blame / history option and you see the last master commits for this were Nov 17th whereas your PR started Nov 18th.

not that i then subsequently made one extra line update via https://github.com/Roche-GSK/admiral/pull/777.

@thomas-neitmann shout if i'm missing anything though - i'm no github expert.

**Comment by thomas-neitmann** [comment]
I know what went wrong. The updated changes are still on the `devel` brnach only. When we merged them there I manually updated the website (since at that point this was the only change, yet). In the meantime one PR by @bms63 accidentally got merged into `master` which triggered the website workflow and overwrote the git vignette with the (old) one on the `master` branch.

**Comment by thomas-neitmann** [comment]
Not quite sure what to do now, though. I do not want to manually create the website from the `devel` branch as that would include new features that are not yet in the latest released package version. I also don't want to merge `devel` into `master`. We really only should do this when we make a new release.

**Comment by bundfussr** [comment]
I see two options:
- We create a branch from master, copy the files from devel into it, add and commit them, and merge the branch into master.
- We use `git rebase` to reapply the commits of the 572_git_usage branch onto master.

**Comment by bms63** [comment]
I think option 1 sounds the easiest.  The files are just the git_ussge.Rmd file and the couple of pngs.  

Okay to proceed with option 1?

**Comment by bundfussr** [comment]
Yes, fine with me.

**Comment by bms63** [comment]
This has been fixed.
