### ISSUE TITLE
update readme

### ISSUE THREAD

**Issue by duniek** [Roche-GSK/admiral#798]
Clarify the difference in our communication channels:
- slack to be used for user support questions etc.
- GitHub for topics related to package development, e.g. bugs, new functions or improving existing ones, etc.

**Comment by rossfarrugia** [comment]
@duniek i can take this on if nobody else has already? as i had to draft some similar wording on this for the pharmaverse site guidance already so can re-use here.

**Comment by thomas-neitmann** [comment]
Feel free to go ahead @rossfarrugia 🙂
