### ISSUE TITLE
Slack channel not accessible to outsiders

### ISSUE THREAD

**Issue by RealSlimMahdi** [Roche-GSK/admiral#812]
Hi there,

<img width="891" alt="CleanShot 2022-01-10 at 13 45 24@2x" src="https://user-images.githubusercontent.com/36238571/148768295-ca3518a5-938d-462e-a048-61ed149c4280.png">

When trying to join the Slack channel as per your documentation, I get the screen above.

Probably the workspace is accessible only to core members.
Maybe something to consider updating once you go public

**Comment by rossfarrugia** [comment]
@RealSlimMahdi thanks for spotting this! it has been updated in our README but not yet made it to main branch (see https://github.com/Roche-GSK/admiral/blob/devel/README.md) - will be in our next release. See the below addition:

If you don't have access, use this [link](https://join.slack.com/t/pharmaverse/shared_invite/zt-yv5atkr4-Np2ytJ6W_QKz_4Olo7Jo9A) to join the pharmaverse Slack workspace. Let me know if any issues!
